services: docker
language: generic

script:
    - SCRIPT=run_build_image.sh
    - curl -O https://raw.githubusercontent.com/cyber-dojo-languages/image_builder/master/${SCRIPT}
    - chmod +x ./${SCRIPT}
    - travis_wait ./${SCRIPT} ${PWD}
