FROM ghcr.io/cyber-dojo-languages/ubuntu-build-essential-24-04:8ab6c08 
LABEL maintainer=pablo.mansanet@bluefruit.co.uk

#COPY install.sh .
#RUN ./install.sh && rm ./install.sh
RUN apt update 
RUN apt install --yes ghdl